html = open('/home/olubu/fintech-data-platform/images/dashboard.html', 'w')

html.write('<!DOCTYPE html>\n')
html.write('<html lang="en">\n')
html.write('<head>\n')
html.write('<meta charset="UTF-8">\n')
html.write('<title>Fintech Pipeline Dashboard</title>\n')
html.write('<style>\n')
html.write('* { box-sizing: border-box; margin: 0; padding: 0; }\n')
html.write('body { background: #0f1117; font-family: monospace; padding: 30px; color: #ffffff; }\n')
html.write('.badge { display: inline-block; font-size: 11px; padding: 3px 10px; border-radius: 99px; }\n')
html.write('.badge-success { background: #1a3a2a; color: #1D9E75; }\n')
html.write('.badge-danger { background: #3a1a1a; color: #E24B4A; }\n')
html.write('.badge-info { background: #0a1a2a; color: #378ADD; }\n')
html.write('.card { background: #1a1d27; border: 1px solid #2d3148; border-radius: 10px; padding: 16px 20px; margin-bottom: 16px; }\n')
html.write('.card-title { font-size: 13px; font-weight: 500; color: #ffffff; margin-bottom: 14px; }\n')
html.write('.metric-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 16px; }\n')
html.write('.metric-card { background: #1a1d27; border: 1px solid #2d3148; border-radius: 10px; padding: 16px; }\n')
html.write('.metric-label { font-size: 12px; color: #a0aec0; margin-bottom: 6px; }\n')
html.write('.metric-value { font-size: 26px; font-weight: 500; color: #ffffff; margin-bottom: 4px; }\n')
html.write('.metric-sub { font-size: 11px; color: #4a5568; }\n')
html.write('.two-col { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 16px; }\n')
html.write('.row { display: flex; align-items: center; justify-content: space-between; padding: 9px 0; border-bottom: 1px solid #2d3148; font-size: 13px; }\n')
html.write('.row:last-child { border-bottom: none; }\n')
html.write('.row-label { color: #a0aec0; }\n')
html.write('.bar-track { flex: 1; background: #2d3148; border-radius: 4px; height: 6px; margin: 0 12px; }\n')
html.write('.bar-fill { height: 6px; border-radius: 4px; }\n')
html.write('.chart-area { display: flex; align-items: flex-end; justify-content: center; gap: 20px; height: 200px; border-bottom: 1px solid #2d3148; }\n')
html.write('.chart-col { display: flex; flex-direction: column; align-items: center; justify-content: flex-end; height: 100%; gap: 6px; }\n')
html.write('.chart-val { font-size: 11px; color: #a0aec0; }\n')
html.write('.chart-bar { width: 56px; border-radius: 4px 4px 0 0; }\n')
html.write('.chart-labels { display: flex; justify-content: center; gap: 20px; margin-top: 10px; }\n')
html.write('.chart-label { font-size: 11px; color: #a0aec0; width: 56px; text-align: center; }\n')
html.write('.footer { text-align: center; font-size: 11px; color: #4a5568; margin-top: 24px; }\n')
html.write('</style>\n')
html.write('</head>\n')
html.write('<body>\n')

html.write('<h1 style="font-size:22px;font-weight:500;margin-bottom:4px;">Fintech Data Platform</h1>\n')
html.write('<p style="font-size:12px;color:#a0aec0;margin-bottom:24px;">Pipeline Dashboard &nbsp;·&nbsp; Last run: 21 May 2026 &nbsp;·&nbsp; <span class="badge badge-success">All systems healthy</span></p>\n')

html.write('<div class="metric-grid">\n')
html.write('<div class="metric-card"><p class="metric-label">Total transactions</p><p class="metric-value">720</p><p class="metric-sub">Bronze layer</p></div>\n')
html.write('<div class="metric-card"><p class="metric-label">Clean records</p><p class="metric-value">720</p><p class="metric-sub">100% pass rate</p></div>\n')
html.write('<div class="metric-card"><p class="metric-label">Total volume</p><p class="metric-value">3.55M</p><p class="metric-sub">Across all categories</p></div>\n')
html.write('<div class="metric-card"><p class="metric-label">Gold aggregations</p><p class="metric-value">5</p><p class="metric-sub">Merchant categories</p></div>\n')
html.write('</div>\n')

html.write('<div class="two-col">\n')
html.write('<div class="card"><p class="card-title">Layer health</p>\n')
html.write('<div class="row"><span class="row-label" style="min-width:60px;">Bronze</span><div class="bar-track"><div class="bar-fill" style="width:100%;background:#BA7517;"></div></div><span class="badge badge-success">720</span></div>\n')
html.write('<div class="row"><span class="row-label" style="min-width:60px;">Silver</span><div class="bar-track"><div class="bar-fill" style="width:100%;background:#888780;"></div></div><span class="badge badge-success">720</span></div>\n')
html.write('<div class="row"><span class="row-label" style="min-width:60px;">Gold</span><div class="bar-track"><div class="bar-fill" style="width:14%;background:#639922;"></div></div><span class="badge badge-info">5 rows</span></div>\n')
html.write('<div class="row"><span class="row-label" style="min-width:60px;">DLQ</span><div class="bar-track"><div class="bar-fill" style="width:30%;background:#E24B4A;"></div></div><span class="badge badge-danger">~30%</span></div>\n')
html.write('</div>\n')

html.write('<div class="card"><p class="card-title">Airflow pipeline runs</p>\n')
html.write('<div class="row"><span class="row-label">run_silver_etl</span><span class="badge badge-success">Success</span></div>\n')
html.write('<div class="row"><span class="row-label">run_gold_etl</span><span class="badge badge-success">Success</span></div>\n')
html.write('<div class="row"><span class="row-label">Schedule</span><span style="font-size:12px;color:#4a5568;">@hourly</span></div>\n')
html.write('<div class="row"><span class="row-label">Next run</span><span style="font-size:12px;color:#4a5568;">11:00 UTC</span></div>\n')
html.write('</div>\n')
html.write('</div>\n')

html.write('<div class="card"><p class="card-title">Gold layer - merchant volume</p>\n')
html.write('<div class="chart-area">\n')
html.write('<div class="chart-col"><span class="chart-val">782k</span><div class="chart-bar" style="height:180px;background:#534AB7;"></div></div>\n')
html.write('<div class="chart-col"><span class="chart-val">717k</span><div class="chart-bar" style="height:165px;background:#0F6E56;"></div></div>\n')
html.write('<div class="chart-col"><span class="chart-val">695k</span><div class="chart-bar" style="height:160px;background:#D85A30;"></div></div>\n')
html.write('<div class="chart-col"><span class="chart-val">685k</span><div class="chart-bar" style="height:157px;background:#854F0B;"></div></div>\n')
html.write('<div class="chart-col"><span class="chart-val">671k</span><div class="chart-bar" style="height:154px;background:#185FA5;"></div></div>\n')
html.write('</div>\n')
html.write('<div class="chart-labels">\n')
html.write('<span class="chart-label">Electronics</span>\n')
html.write('<span class="chart-label">Groceries</span>\n')
html.write('<span class="chart-label">Dining</span>\n')
html.write('<span class="chart-label">Utilities</span>\n')
html.write('<span class="chart-label">Travel</span>\n')
html.write('</div></div>\n')

html.write('<div class="card"><p class="card-title">Transaction count by category</p>\n')
html.write('<div style="display:flex;gap:12px;flex-wrap:wrap;">\n')
html.write('<div style="flex:1;min-width:120px;background:#1a1530;border:1px solid #534AB7;border-radius:8px;padding:14px;text-align:center;"><p style="font-size:22px;font-weight:500;color:#AFA9EC;margin-bottom:4px;">156</p><p style="font-size:11px;color:#534AB7;">Electronics</p></div>\n')
html.write('<div style="flex:1;min-width:120px;background:#0f2a1a;border:1px solid #0F6E56;border-radius:8px;padding:14px;text-align:center;"><p style="font-size:22px;font-weight:500;color:#5DCAA5;margin-bottom:4px;">146</p><p style="font-size:11px;color:#1D9E75;">Groceries</p></div>\n')
html.write('<div style="flex:1;min-width:120px;background:#2a1a0a;border:1px solid #D85A30;border-radius:8px;padding:14px;text-align:center;"><p style="font-size:22px;font-weight:500;color:#F0997B;margin-bottom:4px;">140</p><p style="font-size:11px;color:#D85A30;">Dining</p></div>\n')
html.write('<div style="flex:1;min-width:120px;background:#1a1000;border:1px solid #854F0B;border-radius:8px;padding:14px;text-align:center;"><p style="font-size:22px;font-weight:500;color:#FAC775;margin-bottom:4px;">141</p><p style="font-size:11px;color:#854F0B;">Utilities</p></div>\n')
html.write('<div style="flex:1;min-width:120px;background:#0a1a2a;border:1px solid #185FA5;border-radius:8px;padding:14px;text-align:center;"><p style="font-size:22px;font-weight:500;color:#85B7EB;margin-bottom:4px;">137</p><p style="font-size:11px;color:#378ADD;">Travel</p></div>\n')
html.write('</div></div>\n')

html.write('<div class="card"><p class="card-title">Lineage audit trail</p>\n')
html.write('<div class="row"><span class="row-label">run_20260521_101221</span><span style="color:#4a5568;font-size:12px;">Silver</span><span style="font-size:12px;">720 in to 720 out</span><span class="badge badge-success">100.0%</span></div>\n')
html.write('<div class="row"><span class="row-label">run_20260521_101221</span><span style="color:#4a5568;font-size:12px;">Gold</span><span style="font-size:12px;">720 in to 5 out</span><span class="badge badge-info">aggregated</span></div>\n')
html.write('</div>\n')

html.write('<p class="footer">Fintech Data Platform · Python · Kafka · PySpark · Airflow · Medallion Architecture</p>\n')
html.write('</body>\n')
html.write('</html>\n')

html.close()
print('Dashboard created successfully!')
